In [1]:
people={
    "first":["Abhishek","Ram","Shyam","Mohit"],
    "last":["Karn","Magar","Shah","Awasthi"],
    "email":["abhishek@gmail.com","rammagar@gmail.com","shyamah@yahoo.com","hitashi@gmail.com"],
    "Pass":['Yes',"No","Yes","Yes"],
    "Marks":[97,30,50,86]
}

In [2]:
import pandas as pd

In [3]:
df=pd.DataFrame(people)

In [4]:
df

      first     last               email Pass  Marks
0  Abhishek     Karn  abhishek@gmail.com  Yes     97
1       Ram    Magar  rammagar@gmail.com   No     30
2     Shyam     Shah   shyamah@yahoo.com  Yes     50
3     Mohit  Awasthi   hitashi@gmail.com  Yes     86

In [5]:
df.columns=[x.upper() for x in df.columns]
df

      FIRST     LAST               EMAIL PASS  MARKS
0  Abhishek     Karn  abhishek@gmail.com  Yes     97
1       Ram    Magar  rammagar@gmail.com   No     30
2     Shyam     Shah   shyamah@yahoo.com  Yes     50
3     Mohit  Awasthi   hitashi@gmail.com  Yes     86

In [6]:
df.columns=["First Name","Last Name","EMAIL","PASS","MARK"]
df

  First Name Last Name               EMAIL PASS  MARK
0   Abhishek      Karn  abhishek@gmail.com  Yes    97
1        Ram     Magar  rammagar@gmail.com   No    30
2      Shyam      Shah   shyamah@yahoo.com  Yes    50
3      Mohit   Awasthi   hitashi@gmail.com  Yes    86

In [7]:
df.columns = df.columns.str.replace(' ',"_")
df

  First_Name Last_Name               EMAIL PASS  MARK
0   Abhishek      Karn  abhishek@gmail.com  Yes    97
1        Ram     Magar  rammagar@gmail.com   No    30
2      Shyam      Shah   shyamah@yahoo.com  Yes    50
3      Mohit   Awasthi   hitashi@gmail.com  Yes    86

In [8]:
df.columns=df.columns.str.lower()
df

  first_name last_name               email pass  mark
0   Abhishek      Karn  abhishek@gmail.com  Yes    97
1        Ram     Magar  rammagar@gmail.com   No    30
2      Shyam      Shah   shyamah@yahoo.com  Yes    50
3      Mohit   Awasthi   hitashi@gmail.com  Yes    86

In [9]:
df.rename(columns={'first_name':'first','last_name':'last'},inplace=True)
df

      first     last               email pass  mark
0  Abhishek     Karn  abhishek@gmail.com  Yes    97
1       Ram    Magar  rammagar@gmail.com   No    30
2     Shyam     Shah   shyamah@yahoo.com  Yes    50
3     Mohit  Awasthi   hitashi@gmail.com  Yes    86

In [10]:
df.loc[2,'first']='Sita'
df

      first     last               email pass  mark
0  Abhishek     Karn  abhishek@gmail.com  Yes    97
1       Ram    Magar  rammagar@gmail.com   No    30
2      Sita     Shah   shyamah@yahoo.com  Yes    50
3     Mohit  Awasthi   hitashi@gmail.com  Yes    86

In [11]:
df.loc[2,['last','email']]=['Karna','sitakarna@gmail.com']
df

      first     last                email pass  mark
0  Abhishek     Karn   abhishek@gmail.com  Yes    97
1       Ram    Magar   rammagar@gmail.com   No    30
2      Sita    Karna  sitakarna@gmail.com  Yes    50
3     Mohit  Awasthi    hitashi@gmail.com  Yes    86

In [12]:
df.at[2,'mark']=99
df

      first     last                email pass  mark
0  Abhishek     Karn   abhishek@gmail.com  Yes    97
1       Ram    Magar   rammagar@gmail.com   No    30
2      Sita    Karna  sitakarna@gmail.com  Yes    99
3     Mohit  Awasthi    hitashi@gmail.com  Yes    86

In [13]:
filt=(df['pass']=='No')
df.loc[filt,['pass','mark']]=['Yes',35]
df

      first     last                email pass  mark
0  Abhishek     Karn   abhishek@gmail.com  Yes    97
1       Ram    Magar   rammagar@gmail.com  Yes    35
2      Sita    Karna  sitakarna@gmail.com  Yes    99
3     Mohit  Awasthi    hitashi@gmail.com  Yes    86

In [14]:
df['first']=df['first'].str.lower()
df

      first     last                email pass  mark
0  abhishek     Karn   abhishek@gmail.com  Yes    97
1       ram    Magar   rammagar@gmail.com  Yes    35
2      sita    Karna  sitakarna@gmail.com  Yes    99
3     mohit  Awasthi    hitashi@gmail.com  Yes    86

In [15]:
#apply: used for calling a function on value, work on df or series object
#map
#applymap
#replace

In [16]:
df['email'].apply(lambda x: 'gmail' in x)

0    True
1    True
2    True
3    True
Name: email, dtype: bool

In [17]:
df['email'].apply(str.upper)

0     ABHISHEK@GMAIL.COM
1     RAMMAGAR@GMAIL.COM
2    SITAKARNA@GMAIL.COM
3      HITASHI@GMAIL.COM
Name: email, dtype: str

In [18]:
df

      first     last                email pass  mark
0  abhishek     Karn   abhishek@gmail.com  Yes    97
1       ram    Magar   rammagar@gmail.com  Yes    35
2      sita    Karna  sitakarna@gmail.com  Yes    99
3     mohit  Awasthi    hitashi@gmail.com  Yes    86

In [19]:
df['mark']=df['mark'].apply(lambda x: x/2)

In [20]:
df

      first     last                email pass  mark
0  abhishek     Karn   abhishek@gmail.com  Yes  48.5
1       ram    Magar   rammagar@gmail.com  Yes  17.5
2      sita    Karna  sitakarna@gmail.com  Yes  49.5
3     mohit  Awasthi    hitashi@gmail.com  Yes  43.0

In [21]:
#defualt axis= rows
df.apply(len)

first    4
last     4
email    4
pass     4
mark     4
dtype: int64

In [22]:
df.apply(len,axis='columns')

0    5
1    5
2    5
3    5
dtype: int64

In [23]:
df.apply(lambda x: x.min())

first              abhishek
last                Awasthi
email    abhishek@gmail.com
pass                    Yes
mark                   17.5
dtype: object

In [24]:
df.loc[:, "first":"email"].map(len)

   first  last  email
0      8     4     18
1      3     5     18
2      4     5     19
3      5     7     17

In [25]:
df

      first     last                email pass  mark
0  abhishek     Karn   abhishek@gmail.com  Yes  48.5
1       ram    Magar   rammagar@gmail.com  Yes  17.5
2      sita    Karna  sitakarna@gmail.com  Yes  49.5
3     mohit  Awasthi    hitashi@gmail.com  Yes  43.0

In [27]:
df['first'].map({'abhishek':'Shyam','sita':'geeta'})

0    Shyam
1      NaN
2    geeta
3      NaN
Name: first, dtype: str

In [33]:
df['first']=df['first'].replace({'abhishek':'Shyam','sita':'geeta'})

In [34]:
df

   first     last                email pass  mark
0  Shyam     Karn   abhishek@gmail.com  Yes  48.5
1    ram    Magar   rammagar@gmail.com  Yes  17.5
2  geeta    Karna  sitakarna@gmail.com  Yes  49.5
3  mohit  Awasthi    hitashi@gmail.com  Yes  43.0