In [1]:
people={
    "first":["Abhishek","Ram","Shyam","Mohit"],
    "last":["Karn","Magar","Shah","Awasthi"],
    "email":["abhishek@gmail.com","rammagar@gmail.com","shyamah@yahoo.com","hitashi@gmail.com"],
    "Pass":['Yes',"No","Yes","Yes"],
    "Marks":[97,30,50,86]
}

In [2]:
import pandas as pd

In [3]:
df=pd.DataFrame(people)

In [4]:
df

      first     last               email Pass  Marks
0  Abhishek     Karn  abhishek@gmail.com  Yes     97
1       Ram    Magar  rammagar@gmail.com   No     30
2     Shyam     Shah   shyamah@yahoo.com  Yes     50
3     Mohit  Awasthi   hitashi@gmail.com  Yes     86

In [5]:
df['full_name']=df['first']+' '+ df['last']

In [6]:
df

      first     last               email Pass  Marks      full_name
0  Abhishek     Karn  abhishek@gmail.com  Yes     97  Abhishek Karn
1       Ram    Magar  rammagar@gmail.com   No     30      Ram Magar
2     Shyam     Shah   shyamah@yahoo.com  Yes     50     Shyam Shah
3     Mohit  Awasthi   hitashi@gmail.com  Yes     86  Mohit Awasthi

In [7]:
df.drop(columns=['first','last'],inplace=True)
df

                email Pass  Marks      full_name
0  abhishek@gmail.com  Yes     97  Abhishek Karn
1  rammagar@gmail.com   No     30      Ram Magar
2   shyamah@yahoo.com  Yes     50     Shyam Shah
3   hitashi@gmail.com  Yes     86  Mohit Awasthi

In [9]:
#splitting
df['full_name'].str.split(' ',expand=True)

          0        1
0  Abhishek     Karn
1       Ram    Magar
2     Shyam     Shah
3     Mohit  Awasthi

In [10]:
df[['first','last']]=df['full_name'].str.split(' ',expand=True)

In [11]:
df

                email Pass  Marks      full_name     first     last
0  abhishek@gmail.com  Yes     97  Abhishek Karn  Abhishek     Karn
1  rammagar@gmail.com   No     30      Ram Magar       Ram    Magar
2   shyamah@yahoo.com  Yes     50     Shyam Shah     Shyam     Shah
3   hitashi@gmail.com  Yes     86  Mohit Awasthi     Mohit  Awasthi

In [17]:
#Previous apppend method wont work anymore
pd.concat([df,pd.DataFrame([{'first':'Dinesh','last':'Thagunna'}])],ignore_index=True)

                email Pass  Marks      full_name     first      last
0  abhishek@gmail.com  Yes   97.0  Abhishek Karn  Abhishek      Karn
1  rammagar@gmail.com   No   30.0      Ram Magar       Ram     Magar
2   shyamah@yahoo.com  Yes   50.0     Shyam Shah     Shyam      Shah
3   hitashi@gmail.com  Yes   86.0  Mohit Awasthi     Mohit   Awasthi
4                 NaN  NaN    NaN            NaN    Dinesh  Thagunna

In [24]:
new_rows=[{
    'email':'nihari@gmail.com',
    'Pass':'Yes',
    'Marks': 45.6
}]

In [25]:
pd.concat([df,pd.DataFrame(new_rows)],ignore_index=True)

                email Pass  Marks      full_name     first     last
0  abhishek@gmail.com  Yes   97.0  Abhishek Karn  Abhishek     Karn
1  rammagar@gmail.com   No   30.0      Ram Magar       Ram    Magar
2   shyamah@yahoo.com  Yes   50.0     Shyam Shah     Shyam     Shah
3   hitashi@gmail.com  Yes   86.0  Mohit Awasthi     Mohit  Awasthi
4    nihari@gmail.com  Yes   45.6            NaN       NaN      NaN

In [26]:
df.loc[len(df)] = {'first':'Dinesh','last':'Thagunna'}

In [27]:
df

                email Pass  Marks      full_name     first      last
0  abhishek@gmail.com  Yes   97.0  Abhishek Karn  Abhishek      Karn
1  rammagar@gmail.com   No   30.0      Ram Magar       Ram     Magar
2   shyamah@yahoo.com  Yes   50.0     Shyam Shah     Shyam      Shah
3   hitashi@gmail.com  Yes   86.0  Mohit Awasthi     Mohit   Awasthi
4                 NaN  NaN    NaN            NaN    Dinesh  Thagunna

In [33]:
filt=df['Pass']=='No'
df.drop(index=df[filt].index,inplace=True)
df

                email Pass  Marks      full_name     first      last
0  abhishek@gmail.com  Yes   97.0  Abhishek Karn  Abhishek      Karn
2   shyamah@yahoo.com  Yes   50.0     Shyam Shah     Shyam      Shah
3   hitashi@gmail.com  Yes   86.0  Mohit Awasthi     Mohit   Awasthi
4                 NaN  NaN    NaN            NaN    Dinesh  Thagunna