In [16]:
import pandas as pd
import numpy as np

people = {
    'first': ['Corey', 'Jane', 'John', 'Chris', np.nan, None, 'NA'],
    'last': ['Schafer', 'Doe', 'Doe', 'Schafer', np.nan, np.nan, 'Missing'],
    'email': [
        'CoreyMSchafer@gmail.com',
        'JaneDoe@email.com',
        'JohnDoe@email.com',
        None,
        'Anonymous@email.com',
        None,
        'NA'
    ],
    'age': ['33', '55', '63', '36', None, None, 'Missing']
}

df = pd.DataFrame(people)
df.replace(['NA',"Missing"],np.nan,inplace=True)

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@email.com   55
2   John      Doe        JohnDoe@email.com   63
3  Chris  Schafer                      NaN   36
4    NaN      NaN      Anonymous@email.com  NaN
5    NaN      NaN                      NaN  NaN
6    NaN      NaN                      NaN  NaN

In [17]:
df

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@email.com   55
2   John      Doe        JohnDoe@email.com   63
3  Chris  Schafer                      NaN   36
4    NaN      NaN      Anonymous@email.com  NaN
5    NaN      NaN                      NaN  NaN
6    NaN      NaN                      NaN  NaN

In [18]:
df.dropna()

   first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63

In [19]:
df.dropna(axis='index',how='all')

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@email.com   55
2   John      Doe        JohnDoe@email.com   63
3  Chris  Schafer                      NaN   36
4    NaN      NaN      Anonymous@email.com  NaN

In [20]:
df.dropna(axis='columns',how='all')

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@email.com   55
2   John      Doe        JohnDoe@email.com   63
3  Chris  Schafer                      NaN   36
4    NaN      NaN      Anonymous@email.com  NaN
5    NaN      NaN                      NaN  NaN
6    NaN      NaN                      NaN  NaN

In [21]:
df.dropna(subset=['email'])

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@email.com   55
2   John      Doe        JohnDoe@email.com   63
4    NaN      NaN      Anonymous@email.com  NaN

In [22]:
df.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True  False   True
5   True   True   True   True
6   True   True   True   True

In [23]:
df.fillna(0)

   first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63
3  Chris  Schafer                        0  36
4      0        0      Anonymous@email.com   0
5      0        0                        0   0
6      0        0                        0   0

In [24]:
df['age']=df['age'].astype(float)

In [25]:
df.dtypes

first        str
last         str
email        str
age      float64
dtype: object

In [26]:
df['age'].mean()

np.float64(46.75)