In [10]:
data = {
    "first": [
        "Abhishek",
        "Ram",
        "Shyam",
        "Mohit",
        "Dinesh",
        "Sita",
        "Hari",
        "Gita",
        "Aman",
        "Priya"
    ],
    "last": [
        "Karn",
        "Magar",
        "Shah",
        "Awasthi",
        "Thagunna",
        "Shrestha",
        "Rai",
        "Gurung",
        "Thapa",
        "Karki"
    ],
    "age": [
        21,
        19,
        22,
        20,
        23,
        18,
        21,
        20,
        24,
        19
    ],
    "email": [
        "abhishek@gmail.com",
        "ram@gmail.com",
        "shyam@gmail.com",
        "mohit@gmail.com",
        "dinesh@gmail.com",
        "sita@gmail.com",
        "hari@gmail.com",
        "gita@gmail.com",
        "aman@gmail.com",
        "priya@gmail.com"
    ],
    "marks": [
        85,
        92,
        76,
        88,
        95,
        81,
        69,
        90,
        73,
        87
    ],
    "city": [
        "Kathmandu",
        "Pokhara",
        "Lalitpur",
        "Biratnagar",
        "Butwal",
        "Janakpur",
        "Dharan",
        "Bhaktapur",
        "Chitwan",
        "Hetauda"
    ]
}

In [11]:
import pandas as pd

In [14]:
df=pd.DataFrame(data)

In [15]:
df

      first      last  age               email  marks        city
0  Abhishek      Karn   21  abhishek@gmail.com     85   Kathmandu
1       Ram     Magar   19       ram@gmail.com     92     Pokhara
2     Shyam      Shah   22     shyam@gmail.com     76    Lalitpur
3     Mohit   Awasthi   20     mohit@gmail.com     88  Biratnagar
4    Dinesh  Thagunna   23    dinesh@gmail.com     95      Butwal
5      Sita  Shrestha   18      sita@gmail.com     81    Janakpur
6      Hari       Rai   21      hari@gmail.com     69      Dharan
7      Gita    Gurung   20      gita@gmail.com     90   Bhaktapur
8      Aman     Thapa   24      aman@gmail.com     73     Chitwan
9     Priya     Karki   19     priya@gmail.com     87     Hetauda

In [19]:
df.sort_values(by=['age','last'],ascending=[True,False],inplace=True)

In [20]:
df

      first      last  age               email  marks        city
5      Sita  Shrestha   18      sita@gmail.com     81    Janakpur
1       Ram     Magar   19       ram@gmail.com     92     Pokhara
9     Priya     Karki   19     priya@gmail.com     87     Hetauda
7      Gita    Gurung   20      gita@gmail.com     90   Bhaktapur
3     Mohit   Awasthi   20     mohit@gmail.com     88  Biratnagar
6      Hari       Rai   21      hari@gmail.com     69      Dharan
0  Abhishek      Karn   21  abhishek@gmail.com     85   Kathmandu
2     Shyam      Shah   22     shyam@gmail.com     76    Lalitpur
4    Dinesh  Thagunna   23    dinesh@gmail.com     95      Butwal
8      Aman     Thapa   24      aman@gmail.com     73     Chitwan

In [24]:
##TO get it back, i can just sort by index
df.sort_index(inplace=True)

In [25]:
df

      first      last  age               email  marks        city
0  Abhishek      Karn   21  abhishek@gmail.com     85   Kathmandu
1       Ram     Magar   19       ram@gmail.com     92     Pokhara
2     Shyam      Shah   22     shyam@gmail.com     76    Lalitpur
3     Mohit   Awasthi   20     mohit@gmail.com     88  Biratnagar
4    Dinesh  Thagunna   23    dinesh@gmail.com     95      Butwal
5      Sita  Shrestha   18      sita@gmail.com     81    Janakpur
6      Hari       Rai   21      hari@gmail.com     69      Dharan
7      Gita    Gurung   20      gita@gmail.com     90   Bhaktapur
8      Aman     Thapa   24      aman@gmail.com     73     Chitwan
9     Priya     Karki   19     priya@gmail.com     87     Hetauda

In [27]:
df['last'].sort_values()

3     Awasthi
7      Gurung
9       Karki
0        Karn
1       Magar
6         Rai
2        Shah
5    Shrestha
4    Thagunna
8       Thapa
Name: last, dtype: str